global using Android.Content;
global using Android.OS;
global using Android.Runtime;
global using Android.Webkit;
global using Avalonia.Controls;
global using Avalonia.Platform;
global using Avalonia.Platform.Storage;
global using Avalonia.WebView.Android.Clients;
global using Avalonia.WebView.Android.Common;
global using Avalonia.WebView.Android.Core;
global using Avalonia.WebView.Android.Handlers;
global using Avalonia.WebView.Android.Helpers;
global using AvaloniaWebView.Shared;
global using AvaloniaWebView.Shared.Handlers;
global using Microsoft.Extensions.FileProviders;
global using Microsoft.Extensions.Primitives;
global using System.Buffers;
global using System.Collections;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using WebViewCore;
global using WebViewCore.Configurations;
global using WebViewCore.Events;
global using WebViewCore.Extensions;
global using WebViewCore.Helpers;
global using WebViewCore.Models;
global using static Android.Views.ViewGroup;
global using AndroidApplication = Android.App.Application;
global using AndroidColor = Android.Graphics.Color;
global using AndroidUri = Android.Net.Uri;
global using AndroidWebResourceResponse = Android.Webkit.WebResourceResponse;
global using AndroidWebView = Android.Webkit.WebView;
global using JavaFile = Java.IO.File;
