global using Avalonia.Controls;
global using Avalonia.Platform;
global using Avalonia.WebView.Linux.Helpers;
global using AvaloniaWebView.Shared;
global using AvaloniaWebView.Shared.Handlers;
global using Linux.WebView.Core.Interoperates;
global using Microsoft.Extensions.FileProviders;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Web;
global using WebKit;
global using WebViewCore;
global using WebViewCore.Configurations;
global using WebViewCore.Enums;
global using WebViewCore.Events;
global using WebViewCore.Extensions;
global using WebViewCore.Helpers;
global using WebViewCore.Models;
global using GWindow = Gtk.Window;
global using WebKitWebView = WebKit.WebView;
