global using AppKit;
global using Avalonia.Controls;
global using Avalonia.Platform;
global using AvaloniaWebView.Shared;
global using AvaloniaWebView.Shared.Handlers;
global using Foundation;
global using Microsoft.Extensions.FileProviders;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using WebKit;
global using WebViewCore;
global using WebViewCore.Configurations;
global using WebViewCore.Events;
global using MacosWebView = WebKit.WebView;
